name: Main Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.2
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017

    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v4.0.0
  
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for Mongo to start
        run: |
          until nc -z localhost 27017; do
            sleep 1;
          done        
      - name: Wait for Postgres to start
        run: |
          until nc -z localhost 5432; do
            sleep 1;
          done        

      - name: Generate the gRPC stubs
<<<<<<< HEAD
        uses: spolab/protoc-action@v0.0.11
=======
        uses: spolab/protoc-action@v0.0.12
        env:
          MAPPING: "M=toremo.com/eventstore,paths=source_relative:gen"
>>>>>>> 59cd7f9f3b5419daff53ae571c893ff51e8a3aa7
        with:
          args: protoc -Ischema --go_out=paths=source_relative:gen --go-grpc_out=paths=source_relative:gen ./schema/eventstore.proto

      - name: Test the code
        run: go test ./...

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
