name: Main Workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.2
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Wait for PostgreSQL to start
      #   uses: postgres-check/wait-for-postgres@v1
      #   with:
      #     host: localhost
      #     port: 5432
      #     username: postgres
      #     password: postgres
      #     db_name: test

      - name: Run tests
        run: |
          go run test ./...
