name: Main Workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.2
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017

    steps:
      - name: Install protoc
        run: |
          sudo apt install -y protobuf-compiler protoc-gen-go protobuf-compiler-grpc
    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for Mongo to start
        run: |
          until nc -z localhost 27017; do
            sleep 1;
          done        
      - name: Wait for Postgres to start
        run: |
          until nc -z localhost 5432; do
            sleep 1;
          done        

      - name: Run the build
        run: |
          make
